version: '2.0'
services:
  kokiri:
    build:
      context: .
      dockerfile: deploy/Dockerfile_dev
      args:
        - http_proxy
        - HTTP_PROXY
        - https_proxy
        - HTTPS_PROXY
        - no_proxy
        - NO_PROXY
    ports:
      - '9666:9666'
    volumes:
    - .:/phovea
    environment:
      - ENV=development
      - PYTHONUNBUFFERED=1
